-- Reference data: stations and curriculum catalog.
-- Real production config — every environment (prod, dev, demo) needs this.

-- stations
INSERT INTO stations (id, color, essential, positions) VALUES ('Seeding', '#dc2626', FALSE, ARRAY['Lead','Feeder','Stacker']);
INSERT INTO stations (id, color, essential, positions) VALUES ('Inserts', '#ca8a04', TRUE, ARRAY['Lead','Feeder']);
INSERT INTO stations (id, color, essential, positions) VALUES ('ASRS', '#9333ea', TRUE, ARRAY['Pilot']);
INSERT INTO stations (id, color, essential, positions) VALUES ('Harvest', '#16a34a', TRUE, ARRAY['Lead','Feeder','Catcher','Stacker','Dumper','Corner']);
INSERT INTO stations (id, color, essential, positions) VALUES ('Washing', '#0891b2', FALSE, ARRAY['Feeder','Catcher']);
INSERT INTO stations (id, color, essential, positions) VALUES ('Dirt Removal', '#ea580c', FALSE, ARRAY['Lead','Feeder']);
INSERT INTO stations (id, color, essential, positions) VALUES ('Packaging', '#2563eb', TRUE, ARRAY['Lead','Runner','Weigher','Catcher','Tamper','Case Packer']);

-- curriculum_docs
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('mod-01', 'Onboarding', 'Orientación', 'foundational', 'Module', NULL, 'onboarding', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('mod-02', 'Basic Farming Process', 'Proceso Básico de Cultivo', 'foundational', 'Module', NULL, 'foundations', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('mod-03', 'Cleaning & Sanitation', 'Limpieza y Saneamiento', 'foundational', 'Module', NULL, 'foundations', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('mod-04', 'PPE & Handwashing', 'EPP y Lavado de Manos', 'foundational', 'Module', NULL, 'foundations', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('mod-05', 'Material Handling', 'Manejo de Materiales', 'foundational', 'Module', NULL, 'foundations', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('mod-06', 'Chemical & Worker Safety', 'Seguridad Química y del Trabajador', 'foundational', 'Module', NULL, 'foundations', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('mod-07', 'Basic First Aid', 'Primeros Auxilios Básicos', 'foundational', 'Module', NULL, 'foundations', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('mod-08', 'Incident Response', 'Respuesta a Incidentes', 'foundational', 'Module', NULL, 'foundations', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('seed-sop-001', 'Seed Line Start-Up', 'Inicio de Línea de Siembra', 'station', 'SOP', 'Seeding', 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('seed-ssop-001', 'Seed Drum Cleaning', 'Limpieza de Tambores de Siembra', 'station', 'SSOP', 'Seeding', 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('seed-ssop-002', 'Seeding Machine & Area Cleaning', 'Limpieza de Máquina y Área de Siembra', 'station', 'SSOP', 'Seeding', 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('nut-sop-001', 'Nutrient Mixing – Jack A & B', 'Mezcla de Nutrientes – Jack A y B', 'misc', 'SOP', NULL, 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('nut-ssop-001', 'Nutrient & Water Tank Cleaning', 'Limpieza de Tanques de Nutrientes y Agua', 'misc', 'SSOP', NULL, 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('ins-sop-001', 'Inserting Line Start-Up', 'Inicio de Línea de Inserción', 'station', 'SOP', 'Inserts', 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('asrs-sop-001', 'ASRS Operation', 'Operación del ASRS', 'station', 'SOP', 'ASRS', 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('asrs-sop-002', 'ASRS Components & Controls', 'Componentes y Controles del ASRS', 'station', 'Reference', 'ASRS', 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('asrs-ssop-001', 'ASRS Cleaning & Sanitation', 'Limpieza y Saneamiento del ASRS', 'station', 'SSOP', 'ASRS', 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('wash-ssop-001', 'Lids, Basins & Crates Sanitation', 'Saneamiento de Tapas, Basines y Cajas', 'station', 'SSOP', 'Washing', 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('wash-ssop-003', 'Small LIMEX Washer Cleaning', 'Limpieza de Lavadora LIMEX Pequeña', 'station', 'SSOP', 'Washing', 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('pack-sop-001', 'Label Printing & Case Label Application', 'Impresión y Aplicación de Etiquetas', 'station', 'SOP', 'Packaging', 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('pack-sop-002', 'Lantech Q300 Stretch Wrap Machine', 'Envolvedora Lantech Q300', 'station', 'SOP', 'Packaging', 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('pack-sop-003', 'Pack Line Pre-Operation Startup', 'Inicio Pre-Operación de Empaque', 'station', 'SOP', 'Packaging', 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('pack-sop-004', 'ProSeal Tray Sealer Start-Up', 'Inicio del Sellador ProSeal', 'station', 'SOP', 'Packaging', 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('pack-sop-005', 'BestPack ELVS Carton Erector Start-Up', 'Inicio del Erector BestPack ELVS', 'station', 'SOP', 'Packaging', 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('pack-sop-007', 'Metal Detector Start-Up & Test', 'Inicio y Prueba del Detector de Metales', 'station', 'SOP', 'Packaging', 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('pack-sop-008', 'Yamato TSD-N3 Dataweigh Machine', 'Máquina Yamato TSD-N3 Dataweigh', 'station', 'SOP', 'Packaging', 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('misc-sop-001', 'Chemical Mixing', 'Mezcla de Químicos', 'misc', 'SOP', NULL, 'foundations', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('misc-ssop-001', 'Production Floor Cleaning', 'Limpieza del Piso de Producción', 'misc', 'SSOP', NULL, 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('misc-ssop-002', 'Floor Drains Cleaning & Sanitation', 'Limpieza y Saneamiento de Drenajes', 'misc', 'SSOP', NULL, 'foundations', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('misc-ssop-003', 'Forklift & Floor Scrubber Cleaning', 'Limpieza de Montacargas y Fregadora', 'misc', 'SSOP', NULL, 'proficiency', NULL, NULL);
INSERT INTO curriculum_docs (id, title_en, title_es, category, doc_type, station_id, required_at_stage, link_en, link_es) VALUES ('misc-sop-002', 'Monthly Test & Hold – Tissue Sample Collection', 'Prueba Mensual y Retención – Muestras de Tejido', 'misc', 'SOP', NULL, 'farmer-ready', NULL, NULL);
